{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-python-app.serviceAccountName" . }}
  labels:
    {{- include "my-python-app.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
annotations:
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}

